### ISSUE TITLE
Supervisor not seeing correct Fund Descriptions

### ISSUE THREAD

**Issue by kellanna** [ColoradoEnergyOffice/CEO-Database#4]
Michael Turner is seeing 3 different copies of "agriculture" when selecting fund descriptions for payment requests, and nothing for the k-12 ESS program.

**Comment by pjjohnsonceo** [comment]
Reviewed COA User Table, Michael is assigned all Schools and all Ag funding codes. Checked COA table, all Ag and Schools funding codes are correctly (in)activated. Checked the Payment form, fund description lookup field appears to be correctly filtering for user and active funding sources? I think this is where the problem might be.

**Comment by pjjohnsonceo** [comment]
@ryharry could you take a look at the deluge on the payment form and see if you can spot any issues there? please and thank you!

**Comment by ryharry** [comment]
@kellanna What is the problem? Is there an issue with funding sources showing up on the payment form? What shows up and what doesn't show up? Sorry for the follow up questions, but I need to understand what the problem is. Please let me know. Thanks!

Also, I'll look at it in the meantime to see if I can spot anything weird.

**Comment by ryharry** [comment]
@kellanna does your payment form work OK? I can't find any issues with the filter.

**Comment by kellanna** [comment]
Nope. My available fund descriptions are "Agriculture" "Agriculture" "Agricultural Incentives" CDPHE-870" "CDPHE 950" CDPHE-960" "CDPHE-970" "CDPHE-SEP Misc" and "Industrial" 

Nothing for K-12.

**Comment by pjjohnsonceo** [comment]
OK deleted all the old COA User Table records and imported new ones. Give it a whirl and let me know how it goes! @kellanna

**Comment by kellanna** [comment]
Anna's codes are all correct. I'm assuming Michael's are too. Will open a new ticket later if this appears to not be the case.
