### ISSUE TITLE
Errors occurring on future dates in Service Start & End Date in Payment Request Form

### ISSUE THREAD

**Issue by pjjohnsonceo** [ColoradoEnergyOffice/CEO-Database#5]
Mirka was trying to fill out a Payment Request for a non-award payment for a subscription, and Zoho wouldn't let her enter Service Start or End dates in the future. I think we had set Zoho to regard future service dates as errors because the State has Fiscal Rules against advance payments. However, there are several exceptions to that rule, including for things like subscription payments. CEO makes plenty of advance payments under these exceptions, so I think it makes sense to have the future service dates as a soft error instead of a hard one. That way people might still catch (some) entry errors but are also able to use the form for subscriptions etc. Draft of the error message:

Service (Start/End) Date is entered as a future date. [State Fiscal rules prohibit advance payments except in certain circumstances](https://www.sos.state.co.us/CCR/DisplayRule.do?action=ruleinfo&ruleId=1918&deptID=14&agencyID=40&deptName=Department%20of%20Personnel%20and%20Administration&agencyName=Division%20of%20Finance%20and%20Procurement&seriesNum=1%20CCR%20101-1) (e.g. advertising services, subscriptions, membership dues, interagency agreements, licenses, etc.). Please make sure your dates are entered correctly and/or your payment is an allowable exception.

**Comment by ryharry** [comment]
@pjjohnsonceo I fixed this. For the sake of learning, go ahead into the script for the Start Date and End Date fields and check out the code (https://creator.zoho.com/appbuilder/ryanharry/ceo-operations-database/workflowbuilder/Field_scripts2/edit). For reference to what was there before, I commented out the pre-existing code with the slashes.

**Comment by pjjohnsonceo** [comment]
Thank you! I took a look and everything made total sense -- yay learning!
